### ISSUE TITLE
Installing Rceattle from github

### ISSUE THREAD

**Issue by kristinmarshall-NOAA** [grantdadams/Rceattle#49]
I'm trying to install the Rceattle package according to the vignette instructions: `devtools::install_github("grantdadams/Rceattle", auth_token = "4925b42ac46f1e0aefd671e9dc0c1cf1b3157017", build_vignettes = TRUE)` but am getting an error:
`Error: Failed to install 'Rceattle' from GitHub: arguments imply differing number of rows: 0, 1`

Any ideas?  Thanks!

**Comment by grantdadams** [comment]
can do now its public
